# Generated by Django 3.2.9 on 2021-11-15 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('emoji', models.TextField()),
            ],
            options={
                'db_table': 'emotion',
            },
        ),
        migrations.CreateModel(
            name='DiaryEmotion',
            fields=[
                ('diary_emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=20)),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.diary')),
                ('emotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion.emotion')),
            ],
            options={
                'db_table': 'diary_emotion',
            },
        ),
    ]
