# Generated by Django 3.2.9 on 2021-11-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'managed': False},
        ),
    ]
