# Generated by Django 3.2.9 on 2021-11-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('jacket_url', models.TextField()),
                ('lyric', models.TextField()),
                ('fear', models.FloatField()),
                ('surprise', models.FloatField()),
                ('anger', models.FloatField()),
                ('sadness', models.FloatField()),
                ('neutrality', models.FloatField()),
                ('happiness', models.FloatField()),
                ('disgust', models.FloatField()),
                ('pleasure', models.FloatField()),
                ('embarrassment', models.FloatField()),
                ('unrest', models.FloatField()),
                ('bruise', models.FloatField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
