# Generated by Django 3.2.9 on 2021-11-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('registeration_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diary',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('jacket_url', models.TextField()),
                ('lyric', models.TextField()),
                ('fear', models.FloatField()),
                ('surprise', models.FloatField()),
                ('anger', models.FloatField()),
                ('sadness', models.FloatField()),
                ('neutrality', models.FloatField()),
                ('happiness', models.FloatField()),
                ('disgust', models.FloatField()),
                ('pleasure', models.FloatField()),
                ('embarrassment', models.FloatField()),
                ('unrest', models.FloatField()),
                ('bruise', models.FloatField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Diary_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.diary')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.music')),
            ],
            options={
                'db_table': 'diary_music',
            },
        ),
    ]
